fieldLayouts:
  1b9a4d13-e1e9-4951-b886-0b999a9bd70f:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            autofocus: false
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            required: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 82097eda-17ab-4fc2-a207-c492829f3ddd
            instructions: 'Add a photo to display next to your information.'
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: bf18091a-ed1d-4be3-baa4-ec2d581823b8
            instructions: 'Give some information about yourself.'
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 75
        name: Content
        sortOrder: 1
handle: about
hasTitleField: false
name: About
section: 7695cab0-3ee5-4e11-a5a7-7055e799447a
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
