app: katwamba-mutale
ssh_url: katwamba-mutale@deploy.eu2.frbit.com
git_remote: katwamba-mutale/master
asset_path: web/assets
before:
    code/up:
        - 'echo  "Script example: " $(git rev-parse HEAD)'
after:
    code/down:
        - 'php craft migrate/all'
