fieldLayouts:
  81f3af02-b7c4-46b2-8954-9640c973ed12:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            autofocus: false
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            required: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: static
hasUrls: true
name: Static
settings:
  bucket: $LINODE_S3_BUCKET
  contentDisposition: ''
  endpoint: $LINODE_S3_ENDPOINT
  expires: '3 months'
  keyId: $LINODE_S3_ACCESS_KEY
  region: $LINODE_S3_REGION
  secret: $LINODE_S3_SECRET
  subfolder: static/
sortOrder: 1
type: mwikala\linodes3\Volume
url: $LINODE_S3_BUCKET_URL
