enableVersioning: true
handle: home
name: Home
propagationMethod: all
siteSettings:
  2bfb3976-bc6f-4823-95e0-ed363a19ac96:
    enabledByDefault: true
    hasUrls: true
    template: index
    uriFormat: __home__
type: single
